version: '3.1'
services:
  typescript-project:
    image: marlonjferri/node-with-app
    container_name: typescipt-project
    command: tail -f /dev/null
    volumes:
      - .:/workapp
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workapp